export const categories = ["3D", "AI", "Full Stack", "Real-time"] as const;
export type Category = typeof categories[number];

export const projects = [
    {
        title: "FORGE",
        description: "Community platform that takes ideas from spark to shipped.",
        root: "forge",
        categories: ["Full Stack"],
        slideCount: 7,
        imageExtensions: ["webp", "webp", "webp", "webp", "webp", "webp", "webp"],
        video: "/forge-video.mp4",
        feature: "Project Management, Public Task Boards, Community Voting, Internationalization, Serverless",
        stack: "Next.js, React, TypeScript, Tailwind CSS, Prisma, Neon Postgres, next-intl, Vercel",
        github: "FORGE",
        githubLink: "https://github.com/FaraDuMatin/FORGE",
        site: "FORGE.app",
        siteLink: "https://forge-eight-flame.vercel.app/",
        fullDescription: "Public task boards, credited contributors and open build logs, run the way open source runs software. Only three projects hold the spotlight at once, chosen by readiness criteria and a lottery. Finished projects become forkable playbooks, and signing up needs no account.",
        accentColor: "#3B8C5A"
    },
    {
        title: "FirstClient",
        description: "Practice a full freelance client cycle with a live AI client.",
        root: "firstclient",
        categories: ["AI", "Full Stack", "Real-time"],
        slideCount: 7,
        imageExtensions: ["webp", "webp", "webp", "webp", "webp", "webp", "webp"],
        video: "/firstclient-video.mp4",
        feature: "Voice Agents, AI Evaluation, Computer Vision, Simulation, Real-time",
        stack: "Next.js, React, TypeScript, Tailwind CSS, MongoDB Atlas, ElevenLabs Agents, Gemini API",
        github: "FirstClient",
        githubLink: "https://github.com/FaraDuMatin/FirstClient",
        site: "FirstClient.app",
        siteLink: "https://first-client-weld.vercel.app/",
        fullDescription: "An ElevenLabs voice agent plays the client in a live briefing and scoping call. You submit the work, Gemini reviews it with vision, and the client comes back with revisions. It ends with a debrief on what would have cost you the contract.",
        accentColor: "#593430"
    },
    {
        title: "PLUMB",
        description: "Spatial validation and repair layer between LLM agents and 3D engines.",
        root: "plumb",
        categories: ["AI", "3D", "Full Stack"],
        slideCount: 9,
        imageExtensions: ["webp", "webp", "webp", "webp", "webp", "webp", "webp", "webp", "webp"],
        feature: "FullStack Development, Physics Validation, Constraint Solving, MCP Tooling, 3D Geometry, Agent Integration",
        stack: "Python, FastAPI, FastMCP, TypeScript, React, Three.js, Rerun, Unreal Engine 5",
        github: "PLUMB",
        githubLink: "https://github.com/zajalist/plumb",
        fullDescription: "Checks every placement an LLM agent proposes against physics rules like center of mass and support polygon. When one fails, it returns the exact distance and direction to fix it, not just a rejection. Includes a headless physics engine, an Unreal Engine 5 bridge and an editing studio.",
        accentColor: "#1F2933"
    },
    {
        title: "CollaBoard",
        description: "Collaborative whiteboard with real time features.",
        root: "collaboard",
        categories: ["Full Stack", "Real-time"],
        slideCount: 5,
        imageExtensions: ["mp4", "webp", "webp", "webp", "webp"],
        feature: "Real-time, Multi-user, WebSockets, Authentication, Authorization",
        stack: "Next.js, React, TypeScript, HTML, Tailwind CSS, Convex, Clerk",
        github:"CollaBoard",
        githubLink: "https://github.com/FaraDuMatin/CollaBoard",
        site: "collaboard.app",
        siteLink: "https://colla-board-fwhs.vercel.app/",
        fullDescription: "Several users draw and write on the same board and see each other's changes instantly. Convex keeps every client in sync, and Clerk handles sign-in and access control.",
        accentColor: "#488ce6",
        architecture: "/collaboard.png"
    },
    {
        title: "uOttaMail",
        description: "AI-Powered Inbox Firewall",
        root: "uottamail",
        categories: ["AI", "Full Stack", "Real-time"],
        slideCount: 5,
        imageExtensions: ["webp", "webp", "webp", "webp", "webp"],
        feature: "Spam Detection, Classification, Sentiment Analysis, Multi-agent, Threat Detection",
        stack: "React, Django, PostgreSQL, Redis, Solace Agent Mesh, Docker, LLMs API",
        github: "uOttaMail",
        githubLink: "https://github.com/Divi76h/uOttaMail",
        demo: "Video Demo",
        demoLink: "https://www.youtube.com/watch?v=8X3vqP44T_I/",
        fullDescription: "Several AI agents analyze each incoming email in real time. They flag spam and malicious links, rank priority, read the tone and pull out action items. Built on Solace Agent Mesh with a Django backend.",
        accentColor: "#282c39"
    },
    {
        title: "LLM-Lens",
        description: "LLMO audit tool for analyzing and visualizing LLM outputs.",
        root: "llm-lense",
        categories: ["AI", "Full Stack"],
        slideCount: 6,
        imageExtensions: ["webp", "webp", "webp", "webp", "webp", "webp"],
        video: "/llm-lens-video.mp4",
        feature: "SEO, LLMO, RAG, Web Scraping, Data Visualization",
        stack: "Next.js, React, TypeScript, HTML, Tailwind CSS, Python, FastAPI, Gemini API",
        github: "LLM-Lens",
        githubLink: "https://github.com/FaraDuMatin/llm-lense",
        site: "LLM-Lens.app",
        siteLink: "https://llm-lens-six.vercel.app/",
        fullDescription: "Audits how visible a website is to AI search engines and RAG systems. Think SEO, but for LLMs. A FastAPI service scrapes the site and a Next.js dashboard shows the results.",
        accentColor: "#00e5ff",
        architecture: "/llm-lens.png"
    },
    {
        title: "Fincheck",
        description: "Finance Tracker and Dashboard",
        root: "fincheck",
        categories: ["AI", "Full Stack"],
        slideCount: 5,
        imageExtensions: ["webp", "webp", "webp", "webp", "webp"],
        feature: "Data Analysis, Categorization, REST API, CSV Parsing, Dashboard",
        stack: "Next.js, React, TypeScript, HTML, Tailwind CSS, Python, FastAPI, Gemini API",
        github: "Fincheck",
        githubLink: "https://github.com/FaraDuMatin/FinCheck",
        site: "Fincheck.app",
        siteLink: "https://finchecks.vercel.app//",
        fullDescription: "Upload your transactions as a CSV and each one gets a category automatically. You can correct any of them by hand, and the dashboard summarizes your spending. A FastAPI backend serves the React frontend.",
        accentColor: "#00260b",
        architecture: "/fincheck.png"
    },
    {
        title: "BorderMate",
        description: "Browser-based speech-to-speech translator for real-time conversations.",
        root: "bordermate",
        categories: ["Real-time"],
        slideCount: 3,
        imageExtensions: ["webp", "webp", "webp"],
        feature: "Speech-to-Text, Translation, Text-to-Speech, Real-time, Language Detection",
        stack: "Next.js, React, TypeScript, HTML, Tailwind CSS, APIs",
        github: "BorderMate",
        githubLink: "https://github.com/FaraDuMatin/BorderMate",
        site: "BorderMate.io",
        siteLink: "https://faradumatin.github.io/BorderMate/",
        fullDescription: "Speak, and it transcribes, translates and reads the result aloud in the other language, all in the browser. If one translation service is down, it falls back to the next (LibreTranslate, then Lingva, then MyMemory), so the conversation keeps going.",
        accentColor: "#DECBA4"
    },
    // HIDDEN until luminawave-img1..9.png exist. Uncomment together with the
    // matching entry at the same index in lib/translations/en.ts and fr.ts.
    // {
    //     title: "LuminaWave",
    //     description: "Drop your sound and watch it come to life with mesmerizing visualizations.",
    //     root: "luminawave",
    //     categories: ["3D", "Full Stack", "Real-time"],
    //     slideCount: 9,
    //     imageExtensions: ["png", "png", "png", "png", "png", "png", "png", "png", "png"],
    //     feature: "Audio Visualization, FFT Analysis, 3D Rendering, Real-time, Shareable Captures",
    //     stack: "Next.js, React, TypeScript, Tailwind CSS, Three.js, Web Audio API, Vercel Blob",
    //     github: "LuminaWave",
    //     githubLink: "https://github.com/FaraDuMatin/HackTheMountain2026",
    //     site: "LuminaWave.app",
    //     siteLink: "https://hack-the-mountain2026.vercel.app/",
    //     fullDescription: "LuminaWave turns audio into explorable 3D artwork. It runs a real-time FFT on an MP3 upload, a YouTube link, or live microphone input, maps bass, mid, and high bands to glowing point-cloud trails rendered with Three.js, and lets you fly through the result with WASD controls. Trail style, point shape, smoothing, and sensitivity are all tunable, and any moment can be captured and shared through a unique link.",
    //     accentColor: "#7F8BF7"
    // },
    {
        title: "RayTracer",
        description: "Offline renderer capable of generating realistic 3D images.",
        root: "raytracer",
        categories: ["3D"],
        slideCount: 9,
        imageExtensions: ["webp", "webp", "webp", "webp", "webp", "webp", "webp", "webp", "webp"],
        feature: "Ray Tracing, 3D Rendering, Computer Graphics",
        stack: "C++",
        github: "RayTracingImplementation",
        githubLink: "https://github.com/FaraDuMatin/RayTracingImplementation",
        fullDescription: "A ray tracer written from scratch in C++. It renders 3D scenes with realistic lighting and shadows.",
        accentColor: "#FFFFFF"
    },
    {
        title: "DancingArmadillo",
        description: "Experimentation of glsl shaders",
        root: "armadillo",
        categories: ["3D"],
        slideCount: 6,
        imageExtensions: ["mp4", "webp", "webp", "webp", "webp", "webp"],
        feature: "3D Shaders, WebGL, GLSL, Animation, Interactive",
        stack: "JavaScript, HTML, GLSL, Three.js",
        github: "DancingArmadillo",
        githubLink: "https://github.com/FaraDuMatin/DancingArmadillo",
        site: "DancingArmadillo.io",
        siteLink: "https://faradumatin.github.io/DancingArmadillo/",
        fullDescription: "Custom GLSL shaders drive interactive 3D animation with Three.js. Press P to start the music, then Q, W and E to trigger effects like a DJ.",
        accentColor: "#766ad8"
    },
    {
        title: "CharacterAnimation",
        description: "From building bones to full animation in ThreeJs",
        root: "animation",
        categories: ["3D"],
        slideCount: 4,
        imageExtensions: ["mp4", "webp", "webp", "webp"],
        feature: "3D Rendering, Skeletal Animation, Rigging, Real-time, WebGL",
        stack: "JavaScript, Three.js, GLSL",
        github: "CharacterAnimation",
        githubLink: "https://github.com/FaraDuMatin/CharacterAnimation",
        site: "CharacterAnimation.io",
        siteLink: "https://faradumatin.github.io/CharacterAnimation/",
        fullDescription: "Built for my IFT3355 computer graphics class. You can pose and animate a rigged human model, and keyboard controls trigger animations and show or hide the bones and mesh.",
        accentColor: "#dcceb6"
    }

]